import json, sys, argparse

parser = argparse.ArgumentParser()
parser.add_argument('--input', type = str, help = 'The path to the output file generated by HeapShark')
args = parser.parse_args()
json_file = '../src/heapshark.json'
if(args.input != None):
    json_file = args.input

with open(json_file, 'r') as f:
    data = json.load(f)

metadata = data['metadata']
print('Sampling Rate: ' + str(metadata['samplingRate']))
print('Maximum Number of Frames: ' + str(metadata['maxDepth']) + '\n')

for x in data['events']:
    event_type = x['type']
    if event_type == 0:
        print('MALLOC EVENT:')
    elif event_type == 1:
        print('FREE EVENT:')
    elif event_type == 2:
        print('READ EVENT:')
    elif event_type == 3:
        print('WRITE EVENT:')
    else:
        print('INVALID EVENT: ' + str(x['type']))
        sys.exit()
    print('\tAddress: ' + str(x['addr']))
    print('\tSize: ' + str(x['size']))
    print('\tThread ID: ' + str(x['tid']))
    print('\tTime: ' + str(x['time']))
    if event_type == 0 or event_type == 1:
        print('\tBacktrace: ')
        for y in x['backtrace']:
            if y['path'] == '':
                print('\t\t(NIL)')
            else:
                print('\t\t' + str(y['path']) + ':' + str(y['line']))
